# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions


name: Run cypress tests daily
on:
  schedule:
    # runs cypress test daily at
    - cron: '*/10 * * * *'
jobs:
  nightly:
    runs-on: macos-12
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Install cypress and verify
       run: |
         npm ci
         $(npm bin)/cypress verify
         
     - name: Run Cypress tests
       run: npm run cypress_run
       continue-on-error: false
       
     - name: Copy test execution videos
       run: |
         mkdir public
         cp -r cypress/videos public/videos
         
     - name: Deploy report page to Github Page
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./public
